language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - pip install coveralls
script:
  nosetests --cover-branches --with-coverage --cover-package singing_girl
after_success:
  coveralls
